blank_issues_enabled: false
contact_links:
  - name: Kryonite Labs Security
    url: https://kryonite.org/docs/overview#security-vulnerabilities
    about: Please report security vulnerabilities here.